### ISSUE TITLE
[Server Crash] - Fabric 1.18.2 - Some Light Error

### ISSUE THREAD

**Issue by xR4YM0ND** [Sjouwer/immortal-coral#1]
( I flew around the map , generating chunks and first i got kicked from the server. Then i removed "Smooth chunk loading" (only server-side nesseccarry). Started server again and joined and now the server crashes.

Some kind person on Fabric Discord said: Remove Immortal Coral & now it works, i can join my server again. 

So here are the 2 latest.logs:

[first latest.log](https://gist.github.com/SpigotDE/492526118abe575af25d77a148da2688)

[Second latest.log](https://gist.github.com/SpigotDE/3800b97f5971719e2dfdfc37d0b783e4)

**Comment by xR4YM0ND** [comment]
BTW your Issues link on modrinth is not working

**Comment by Sjouwer** [comment]
Thanks a lot for the report
I have a feeling I know what went wrong, the mod probably tries to use client code while running on the server. I should have thought of testing the server side more, it's what I get from only ever working on client stuff.

I'll try to fix the server side asap

Also thanks for letting me know about the issue link, tha'ts fixed now
