### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by K0KE11** [Sjouwer/immortal-coral#3]
When placing the coral blocks it works like normal which means they do die. I'm using this version: Immortal-Coral-1.9.5-mc1.21

**Comment by Sjouwer** [comment]
The mod adds a gamerule that you need to enable as mentioned in the mods description:
Use `/gamerule immortalCoral true` to enable this mod in your world.

**Comment by K0KE11** [comment]
Yeah hahaha thanks just read the description and came to erase the issue lmao thanks tho
